tm-fe/FlexTable

test/unit/specs/resizable.spec.ts, test/unit/specs/scrollBar.spec.ts, test/unit/specs/selectable.spec.ts
=> test:select在无数据的测试

examples/features/fixedHeader.vue, src/table.vue
=> fix:修复没数据时，设定高度找不到flex-table-tr报错问题

examples/features/expand.vue, src/table.vue, src/tableTd.vue, test/index.d.ts
=> feat:添加expandStatus传参状态

package-lock.json, test/unit/specs/initRowNumber.spec.ts
=> test:增加initRowNumber的测试

src/table.vue
=> feat:增加body滚动$emit事件

examples/features/index.vue, src/table.vue
=> feat:修改$emit事件为x轴滚动&demo

test/unit/specs/resizable.spec.ts
=> test:增加列宽不可调整宽度的单元测试

examples/app.vue, examples/features/selectable.vue, examples/routes.js, readme.md, src/css/main.less, src/table.vue
=> feat:增加全屏固定头部&固定列样式

src/table.vue
影响表格的resize和窗体改变是的渲染
修复doLayout中debounce作用域问题
=> fix:修复doLayout中debounce作用域问题

examples/features/footer.vue, src/slot.js, src/tableFoot.vue
在slot中增加了样式，type('body'|'foot')以及对应的key，可实现汇总列的slot渲染
可以通过type判断是属于body还是foot的渲染，可以通过key来获取当前的列（动态slot名称时使用）
=> Dev sum slot

src/table.vue
增加autoCalWidth配置项,默认true,false时会严格按照设置的width来展示
针对有些情况需要按照严格设置的width来展示，目前的自动计算会影响了width的设置
=> feat:增加autoCalWidth配置项,默认true,false时会严格按照设置的width来展示

src/table.vue
=> fix:修复autoCalWidth:false时,计算宽度大于表格宽度时出现双滚动条

src/tableHead.vue
=> Dev fix header selection state

src/tableHead.vue
=> fix: 修复空数据场景表格选中状态错误问题

src/tableHead.vue, src/tableTr.vue
=> fix: 修复固定列对齐问题

src/css/main.less, src/table.vue
=> feat: 添加固定列阴影

examples/features/index.vue, readme.md, src/css/main.less, src/table.vue
=> feat: 新增固定横向滚动条

src/table.vue, src/tableTr.vue
=> fix: 修复固定列表头阴影问题

src/css/main.less
=> style: 修改CheckBox选中样式为蓝底白字

examples/features/index.vue, package.json, src/table.vue
1. 修复uniqueKey问题
2. 修复固定横向滚动条问题
3. 修复报错问题
=> fix: 修复固定横向滚动条问题

package.json, src/css/main.less, src/tableHead.vue
=> feat: 修改表头结构和样式

examples/features/index.vue, package.json, src/table.vue, src/tableBody.vue, src/tableTd.vue, src/tableTr.vue
=> fix: 修复enableRowCheck开启时点击checkbox回3次；on-row-click阻止checkbox原生事件

package.json, src/tableBody.vue
=> feat: 去掉flexTable最后一行的border样式

src/tableTr.vue
=> fix: 修复行对齐问题

src/table.vue, src/tableTr.vue
=> fix: 修复表格容器尺寸变化后未重新计算列宽问题

package.json, src/table.vue
=> feat:抛出hover行事件

examples/features/autoCalWidth.vue, examples/features/index.vue, examples/features/sortable.vue, package-lock.json, src/Spinner.vue, src/css/main.less, src/mixin.js, src/table.vue, src/tableBody.vue, src/tableHead.vue, src/tableSum.vue, src/tableTd.vue, src/tableTr.vue
=> Refactor fixed

src/css/main.less
=> fix: 优化横向固定滚动条

package.json, src/table.vue
=> fix：修正，最后一列宽度应该大于最后计算出来的平均宽度

examples/features/index.vue, src/table.vue
=> feat: 固定汇总行功能

package.json
=> feat:修改版本号

examples/features/fixedLeft.vue, package.json, src/css/main.less, src/table.vue, src/tableBody.vue, src/tableFoot.vue, src/tableHead.vue, src/tableScrollBar.vue, src/tableSum.vue, src/tableTd.vue, src/tableTr.vue
=> 样式计算、行点击优化

src/table.vue, src/tableBody.vue, src/tableTd.vue, src/tableTr.vue
=> perf：优化表格滚动性能，避免滚动过程中的全量刷新
